[profile.release]
panic = 'unwind'

[workspace]
exclude = [
    "utils/webpki",
    "utils/ring",
    "utils/serde_json_no_std",
    "utils/serde_derive_no_std",
    "utils/serde_derive_no_std",
    "cumulus"
]

members = [
    'cstrml/balances',
    'cstrml/candy',
    'cstrml/claims',
    'cstrml/staking',
    'cstrml/swork',
    'cstrml/market',
    'cstrml/swork/benchmarking',
    'crust-collator',
    'runtime',
    'rpc',
    'node',
]