[package]
authors = ['crustio']
edition = '2018'
name = 'crust-runtime'
version = '0.10.0'
build = 'build.rs'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.5'

[dependencies]
# third party dependencies
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '1.3.4' }
serde = { features = ['derive'], optional = true, version = '1.0.116' }
static_assertions = "1.1.0"

# substrate frame dependencies
pallet-authorship = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-authority-discovery = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-babe = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-collective = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-grandpa = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-indices = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", default-features = false }
pallet-im-online = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-randomness-collective-flip = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-session = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-staking-reward-curve = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-scheduler = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-offences = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-treasury = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-bounties = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-tips = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-elections-phragmen = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-democracy = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-membership = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-identity = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72"}
pallet-utility = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }

frame-executive = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", optional = true }
frame-system-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", optional = true }

# Used for the crust's RPCs
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }

# substrate primitives
authority-discovery-primitives = { default-features = false, package = 'sp-authority-discovery', git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
babe-primitives = { default-features = false, package = 'sp-consensus-babe', git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-block-builder = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-inherents = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-offchain = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-session = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-staking = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-transaction-pool = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-version = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-runtime-interface = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }

# crust runtime modules
swork = { version = "0.10.0", package = 'cstrml-swork', path = '../cstrml/swork', default-features = false }
staking = { version = "0.10.0", package = 'cstrml-staking', path = '../cstrml/staking', default-features = false }
market = { version = "0.10.0", package = 'cstrml-market', path = '../cstrml/market', default-features = false }
primitives = { version = "0.10.0", package = 'cst-primitives', path = '../primitives', default-features = false }
balances = { version = "0.10.0", package = 'cstrml-balances', path = '../cstrml/balances', default-features = false }
candy = { version = "0.10.0", package = 'cstrml-candy', path = '../cstrml/candy', default-features = false  }

[features]
default = ['std']
std = [
    'pallet-authorship/std',
    'authority-discovery-primitives/std',
    'pallet-authority-discovery/std',
    'pallet-babe/std',
    'babe-primitives/std',
    'balances/std',
    'codec/std',
    'pallet-collective/std',
    'frame-executive/std',
    'frame-support/std',
    'pallet-grandpa/std',
    'pallet-im-online/std',
    'pallet-indices/std',
    'pallet-randomness-collective-flip/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-staking/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'pallet-sudo/std',
    'pallet-session/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-scheduler/std',
    'pallet-offences/std',
    'pallet-treasury/std',
    'pallet-bounties/std',
    'pallet-tips/std',
    'pallet-elections-phragmen/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-democracy/std',
    'pallet-membership/std',
    'pallet-utility/std',
    'pallet-identity/std',
    'sp-runtime-interface/std',
    'swork/std',
    'staking/std',
    'market/std',
    'primitives/std',
    'candy/std'
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "balances/runtime-benchmarks",
    "frame-system-benchmarking",
    "staking/runtime-benchmarks",
    "market/runtime-benchmarks",
    "swork/runtime-benchmarks"
]