[package]
name = 'crust'
version = '0.10.0'
authors = ['crustio']
build = 'build.rs'
edition = '2018'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[[bin]]
name = 'crust'

[dependencies]
# third parity dependencies
futures = "0.3.4"
log = "0.4.8"
structopt = { version = '0.3.8', optional = true }
hex-literal = "0.2.1"

# substrate client dependencies
authority-discovery = { package = 'sc-authority-discovery', git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-finality-grandpa  = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-client-api = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-cli = {  git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", features = ["wasmtime"], optional = true }
sc-consensus = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-executor = {  git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", features = ["wasmtime"] }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sc-service = {  git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", features = ["wasmtime"] }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }

# substrate primitives
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-consensus = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-inherents = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-io = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", optional = true }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }

# crust runtime modules
crust-runtime = { path = '../runtime', version = '0.10.0' }
cstrml-staking = { path = '../cstrml/staking', version = '0.10.0' }
cstrml-swork = { path = '../cstrml/swork', version = '0.10.0' }
primitives = { package = 'cst-primitives', path = '../primitives', version = '0.10.0' }
crust-rpc = { path =  '../rpc', version = '0.10.0' }

[build-dependencies]
build-script-utils = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72",  package = "substrate-build-script-utils", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", optional = true }

[features]
default = [ "cli" ]
cli = [
    "wasmi-errno",
    "sc-cli",
    "frame-benchmarking-cli",
    "sc-service/db",
    "structopt",
    "build-script-utils",
]

runtime-benchmarks = [
    "crust-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
]

wasmtime = [
    "sc-executor/wasmtime",
]

wasmi-errno = [
    "sc-executor/wasmi-errno",
]