[package]
name = "cstrml-swork"
version = "0.10.0"
authors = ["crustio"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[dependencies]
# third party dependencies
codec = { default-features = false, package = 'parity-scale-codec', version = '1.3.4' }
serde = { optional = true, version = '1.0.116' }
base64 = { version = "0.12.2", default-features = false, features = ["alloc"] }
p256 = { version = "0.5.1", default-features = false, features = ["ecdsa"] }

# substrate frame dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }

# substrate primitives
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-runtime-interface = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72", default-features = false, optional = true }

# crust runtime modules
market = { version = "0.10.0", package = 'cstrml-market', path = '../market', default-features = false }
primitives = { version = "0.10.0", package = 'cst-primitives', path = '../../primitives', default-features = false }
webpki = { version = "0.21.0", package = 'webpki', path = '../../utils/webpki', default-features = false }
serde_json = { version = "1.0.59", package = "serde_json_no_std", path = '../../utils/serde_json_no_std', default-features = false, features = ["alloc"] }

[dev-dependencies]
keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
balances = { version = "0.10.0", package = 'cstrml-balances', path = '../balances' }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "532cce0118fe7a64168413e638b177e7e144ef72" }
hex = '0.4.2'

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
    'sp-std/std',
    'frame-system/std',
    'sp-runtime-interface/std',
    'market/std',
    'primitives/std',
    'webpki/std'
]
runtime-benchmarks = [
    "frame-benchmarking",
]